---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: finops-arbitrage-router-fallback
  namespace: finops-arbitrage-router
spec:
  encryptedData:
    api-key: AgCYY/pNea+rJMVwEynTTYd2uRPv0x8xqdoOX/NiXA+XbB+N7pOG5oSvaXSxRwjb00M+8+V9DcctggTwHHQLTK7JyPpDP1lZdC/7Px4ZXljQu19oejPkdZBoMSiTiQXPrC0mg4y5kmLy4t61nUUHCIlGDLVDWjny3Q6ppJp9aPZHHSs19AczedWvJ56EkGw6sGGrC8yQDS974vnYRiWblR9xOzav1gXIY8CKCY9FmXGKCBpUi3yC5O6B4jhOxv/lNj/8wrRbq9peswfUQ4yVIWwrP3PspRHNQGe2QsZhVTeV8CKHzw+oevqpaH7YjFSBCtUmRDkzmnyAhNebYY0iyWviaLbRmZisXDEDzQ2FtZLbBlXBBXT8ajSkFRXdmSpmgQwyF6Uvwazuptzct6DSzvLjlxHHx/bmsDKBitqHOJ74Y/T7X2JWEPCxpjgBGs9Vhc1hYkNQrR5d6/NdFhinpqZrBdhoc0x2BDCzHTJI+XCmfcR5NI3XRO6Z9M59jcP2IVW/fICgLmmsfoRo4gOx3X5BfFkhJ5Vi6Dmf/JeW+jF4nIaWxXhBXsZVeLqUoM+7Xt2Ngr17e5owC3TErNF/3am5iiLzBDLs/q4CyB+wn4udNpFkC+GEMgyWeDoNszI/sryIMt7MmSAnf8daRng5/owIjxEg97rLg1PJoRgvbxjVUPvD+QaAU/O/cwd0QIjn+fjizGfa1Ie7SyJ5XvoU0XaoNBxlYuokWoGoXO+8qe1NsebjaA==
  template:
    metadata:
      creationTimestamp: null
      name: finops-arbitrage-router-fallback
      namespace: finops-arbitrage-router
